### PR TITLE
Update versions to GNOME Sdk 44

### PR DESCRIPTION
**Pull request by jwharm**
- Updated the Flatpak org.gnome.Sdk version to 44.
- Updated the versions of the gir files to correspond with the Flatpak version.

### CODE REVIEW

**Comment by jwharm** [comment]
The second commit bumps GStreamer and Harfbuzz max versions to accept the updated versions on Brew and Msys.

**Review by badcel — CHANGES_REQUESTED** [review]
Thanks for your PR. I think you missed GTK. On the other hands there are some packages which I think should be held back as the gnome-sdk is not there yet. See my comments for details.

Please squash your commits into one so we only get one commit for all your changes before merging.

**Comment by badcel** [comment]
According to your comment:
> The second commit bumps GStreamer and Harfbuzz max versions to accept the updated versions on Homebrew and MSYS2.
It sounds like you want to allow newer versions of libraries for win/mac. This would be against the changes you introduced in the transfer script from my point of view? We wanted to limit the version, to keep all platforms gir-files in lockstep.

How do you generate the bindings for different platforms? Are they independent from each other? I generate currently only one binary which can be consumed by all paltforms. Therefore I need to choose which gir defines the available API. For me this is the gnome-sdk. I use the gir files for mac / win to determine if some API is not available on a specific platform. This is the reason why I want to keep the gir files in sync between platforms and explicitly not allow one platform to have a different major version.

**Comment by jwharm** [comment]
I completely agree, which is why I initially updated to the versions of the gnome-sdk (though I somehow forgot to change the version for Gtk, oops).

However, according to the logs of the Github actions for [win](https://github.com/gircore/gir-files/actions/runs/4761030290/jobs/8461902795#step:5:18) and [mac](https://github.com/gircore/gir-files/actions/runs/4760623162/jobs/8461120375#step:5:16), they are already on newer versions of HarfBuzz and GStreamer. If we don't set the max version to include them, I'm afraid that they will forever stay one version ahead of gnome-sdk and therefore never update in the gir-files repository. That's why I made a second commit, to increase these versions too.

I'm not really sure what the best solution is. Maybe freedesktop-sdk and gnome-sdk will update to the newer versions soon anyway.

I will update the PR to only update the max version numbers to the gnome-sdk versions.

**Comment by jwharm** [comment]
I had to force push after squashing the commits.

**Comment by badcel** [comment]
Force pushing is very welcome, as long as it does happen on branches which are work in progress and not `main`  :+1:

Hm, I can try to ask someone from gnome if they intend to update GStreamer / freedesktop sdk or if they want to wait for the next 6 month.

We can consider on how to progress if we have some answer. For now this looks good to me, thank you.

**Review by badcel — APPROVED** [review]

**Pull request merged**
