### PR TITLE
Check library versions

### PR DESCRIPTION
**Pull request by jwharm**
Changed the script to read the library filename (as used by `pkg-config`) and the maximum version numbers (as reported by `pkg-config`) from the input file, and only update the gir file in the repository when the new version is below the maximum version.

This will prevent unexpected updates of the gir files to new versions one one platform while the others are still on an older version.

### CODE REVIEW

**Comment by jwharm** [comment]
The logs of a test run can be found here:
https://github.com/jwharm/gir-files/actions/runs/4484105309/jobs/7884212287#step:5:1

**Comment by badcel** [comment]
This looks pretty good already. Some suggestions:
 - I could imagine that it would make working with the repository easier if the python script would print the versions of all packages it considers for copying. This allows to verify the version numbers and do some investigations regarding certain version numbers etc.
- If a package is copied from the backup folder it is probably worth an extra print message to make clear that this package is newer than the maximum version number.

Are you interested in adding those points?

**Comment by jwharm** [comment]
Yes, that could be helpful.
I've added an extra line of logging with the version. Output:
https://github.com/jwharm/gir-files/actions/runs/4494426366/jobs/7906898337#step:5:1

**Comment by badcel** [comment]
Can you update the `print` command to something like:

`print(f"Found {pkg} version: {modversion} (must be lower {nextversion})")`

Then we have the important information in one line available and it's good to go 👍.

**Comment by jwharm** [comment]
Test output:
https://github.com/jwharm/gir-files/actions/runs/4494604886/jobs/7907286888#step:5:1

**Pull request merged**
